version: '3'
services:
  app:
    # image: server:v1
    # for private images
    image: 703810905347.dkr.ecr.us-east-1.amazonaws.com/basicapp:latest
    ports: 
      - 3000:3000
    depends_on: 
      - mongodb
    networks: 
      - mongonet
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    networks: 
      - mongonet
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on: 
      - mongodb
    networks: 
      - mongonet
volumes:
  mongo-data:
    driver: local
networks: 
  mongonet:
    driver: bridge